/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaControlador;

import Interfaces.ColorObserver;
import Modelo.Datos;
import Modelo.BBDD;
import java.awt.Color;
import java.awt.MouseInfo;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;

/**
 *
 * @author ASUS
 */
public class NuevoUsuario extends javax.swing.JFrame implements ColorObserver {

    private String Usuario;
    private String Contraseña;
    private BBDD bd = BBDD.getInstancia();
    private int xx, xy;

    public NuevoUsuario() {
        this.bd = Datos.basedeDatos;

        initComponents();
        
        this.setTitle("Agregar nuevo usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JL_Usu = new javax.swing.JLabel();
        JL_Contraseña = new javax.swing.JLabel();
        JL_ConfirmarContraseña = new javax.swing.JLabel();
        JL_Nombre = new javax.swing.JLabel();
        JL_Apellidos = new javax.swing.JLabel();
        JL_Correo = new javax.swing.JLabel();
        JL_Fecha = new javax.swing.JLabel();
        Usuariotx = new javax.swing.JTextField();
        Nombretx = new javax.swing.JTextField();
        correotx = new javax.swing.JTextField();
        Apellidotx = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cabecera = new javax.swing.JPanel();
        JL_Xsalir = new javax.swing.JLabel();
        JL_minimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-yoga-60.png"))); // NOI18N
        jLabel2.setText("Por favor, introduzca la informacion del nuevo usuario");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kisspng-mandala-designs-drawing-zentangle-coloring-book-mandala-rainbow-interesting-freetoedit-5b62cf20ecc350.4401150415332022089698.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        JL_Usu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JL_Usu.setForeground(new java.awt.Color(255, 255, 255));
        JL_Usu.setText("Usuario");

        JL_Contraseña.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JL_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        JL_Contraseña.setText("Contraseña");

        JL_ConfirmarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JL_ConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        JL_ConfirmarContraseña.setText("Confimar contraseña");

        JL_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JL_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        JL_Nombre.setText("Nombre");

        JL_Apellidos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JL_Apellidos.setForeground(new java.awt.Color(255, 255, 255));
        JL_Apellidos.setText("Apellido");

        JL_Correo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JL_Correo.setForeground(new java.awt.Color(255, 255, 255));
        JL_Correo.setText("Correo");

        JL_Fecha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JL_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        JL_Fecha.setText("Fecha de nacimiento");

        Nombretx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombretxKeyTyped(evt);
            }
        });

        correotx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                correotxFocusLost(evt);
            }
        });

        Apellidotx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidotxKeyTyped(evt);
            }
        });

        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-izquierda-círculo-50_1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(JL_Apellidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Apellidotx, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(JL_Fecha)
                                        .addGap(3, 3, 3))
                                    .addComponent(JL_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JL_ConfirmarContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JL_Usu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JL_Contraseña, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(JL_Correo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Usuariotx, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombretx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(correotx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Usu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuariotx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Contraseña)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_ConfirmarContraseña)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Nombre)
                    .addComponent(Nombretx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Apellidos)
                    .addComponent(Apellidotx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correotx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Correo))
                .addGap(35, 35, 35)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JL_Fecha)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        Cabecera.setBackground(new java.awt.Color(204, 0, 204));
        Cabecera.setForeground(new java.awt.Color(255, 153, 0));
        Cabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CabeceraMouseDragged(evt);
            }
        });
        Cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CabeceraMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CabeceraMousePressed(evt);
            }
        });
        Cabecera.setLayout(null);

        JL_Xsalir.setBackground(new java.awt.Color(255, 255, 255));
        JL_Xsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salirX.png"))); // NOI18N
        JL_Xsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_XsalirMouseClicked(evt);
            }
        });
        Cabecera.add(JL_Xsalir);
        JL_Xsalir.setBounds(730, 10, 20, 20);

        JL_minimizar.setBackground(new java.awt.Color(164, 189, 152));
        JL_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.jpg"))); // NOI18N
        JL_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_minimizarMouseClicked(evt);
            }
        });
        Cabecera.add(JL_minimizar);
        JL_minimizar.setBounds(700, 10, 20, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JL_XsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_XsalirMouseClicked
        System.exit(0);// Cierra la aplicacion
    }//GEN-LAST:event_JL_XsalirMouseClicked

    private void JL_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_minimizarMouseClicked
        setExtendedState(Login.ICONIFIED);
    }//GEN-LAST:event_JL_minimizarMouseClicked

    private void CabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CabeceraMouseDragged

        setLocation((int) MouseInfo.getPointerInfo().getLocation().getX() - xx, (int) MouseInfo.getPointerInfo().getLocation().getY() - xy);
    }//GEN-LAST:event_CabeceraMouseDragged

    private void CabeceraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CabeceraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CabeceraMouseClicked

    private void CabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CabeceraMousePressed
        xx = ((int) MouseInfo.getPointerInfo().getLocation().getX() - getX());
        xy = ((int) MouseInfo.getPointerInfo().getLocation().getY() - getY());
    }//GEN-LAST:event_CabeceraMousePressed

    private void NombretxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombretxKeyTyped
        //CONTROLO SOLO ENTRAN LETRAS
        char c = evt.getKeyChar();// es utilizado para obtener el carácter correspondiente a una tecla presionad
        if ((c < 'a' | c > 'z') && (c < 'A' | c > 'Z') && (c < ' ' | c > ' '))
            evt.consume();
    }//GEN-LAST:event_NombretxKeyTyped

    private void ApellidotxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidotxKeyTyped
        //CONTROLO SOLO ENTRAN LETRAS
        char c = evt.getKeyChar();// es utilizado para obtener el carácter correspondiente a una tecla presionad
        if ((c < 'a' | c > 'z') && (c < 'A' | c > 'Z') && (c < ' ' | c > ' '))
            evt.consume();
    }//GEN-LAST:event_ApellidotxKeyTyped

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        Login Pl = new Login();
        Pl.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void correotxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correotxFocusLost
        if (ValidacionCorreo(correotx.getText()) == true) {
            correotx.setBorder(BorderFactory.createLineBorder(Color.GREEN));
        } else {
            correotx.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
    }//GEN-LAST:event_correotxFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String usuario = Usuariotx.getText();
        String contrasena = jPasswordField1.getText().toString();
        String confirmacion = jPasswordField2.getText().toString();
        String nombre = Nombretx.getText();
        String apellido = Apellidotx.getText();
        String correo = correotx.getText().trim();// elimina espacios en blanco delante y detras

        Date fechaSeleccionada = jDateChooser1.getDate();
        String fechaComoString = null;

       
            if (fechaSeleccionada != null) {
                SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                fechaComoString = formato.format(fechaSeleccionada);
            }
        

        if (nombre.isEmpty()) {
            nombre = null;
        }
        if (apellido.isEmpty()) {
            apellido = null;
        }

        if (contrasena.equals(confirmacion)) {
            jPasswordField2.setBorder(BorderFactory.createLineBorder(Color.GREEN));
            bd.GuardarUsuario(usuario, contrasena, nombre, apellido, fechaComoString, correo);
             javax.swing.JOptionPane.showMessageDialog(this, "Usuario añadido exito!.", "ENHORABUENA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            jPasswordField2.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean ValidacionCorreo(String email) {
        // Expresión regular para validar direcciones de correo electrónico
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidotx;
    private javax.swing.JPanel Cabecera;
    private javax.swing.JLabel JL_Apellidos;
    private javax.swing.JLabel JL_ConfirmarContraseña;
    private javax.swing.JLabel JL_Contraseña;
    private javax.swing.JLabel JL_Correo;
    private javax.swing.JLabel JL_Fecha;
    private javax.swing.JLabel JL_Nombre;
    private javax.swing.JLabel JL_Usu;
    private javax.swing.JLabel JL_Xsalir;
    private javax.swing.JLabel JL_minimizar;
    private javax.swing.JTextField Nombretx;
    private javax.swing.JTextField Usuariotx;
    private javax.swing.JTextField correotx;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateColor(Color newStartColor, Color newEndColor) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
